//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MusicLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public Album()
        {
            this.AlbumArts = new HashSet<AlbumArt>();
            this.Songs = new HashSet<Song>();
        }
        
        [ScaffoldColumn(false)]
        public int albumID { get; set; }
        [DisplayName("Album Title")]
        public string name { get; set; }
        public Nullable<int> artistID { get; set; }
        public Nullable<int> genreID { get; set; }
        [DisplayName("Year Released")]
        public Nullable<int> releaseYear { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual ICollection<AlbumArt> AlbumArts { get; set; }
        public virtual ICollection<Song> Songs { get; set; }
    }
}
